# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    make \
    gcc \
    git \
    curl \
    bash \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the entire repository into the container
COPY . .

# Set up Python virtual environment and install dependencies
RUN python -m venv diffugen_env \
    && . diffugen_env/bin/activate \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

# Use bash explicitly for the entrypoint as diffugen.sh uses bash-specific syntax.
ENTRYPOINT [ "bash", "diffugen.sh" ]
